apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: manufacturer-restserver
  namespace: manufacturer-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  chart:
    path: platforms/hyperledger-fabric/charts/fabric-restserver
    git: ssh://git@github.com/craig8/blockchain-automation-framework.git
    ref: local
  releaseName: manufacturer-restserver
  values:
    metadata:
      namespace: manufacturer-net
    server:
      name: manufacturer-restserver
      port: 20001
      localmspid: manufacturerMSP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric/rest_server:latest
      username: admin
      cert_path: "/secret/tls/admin.cert"
      key_path: "/secret/tls/admin.pem"
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      address: http://192.168.1.135:8200
      role: vault-role
      authpath: manufacturer-net-auth
      secretprefix: secret/crypto/peerOrganizations/manufacturer-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.manufacturer-net
      peerAddress: peer0.manufacturer-net
      peerPort: 7051
      ordererAddress: orderer1.supplychain-net
      ordererPort: 7050